/**
 * The TypeScript rules must agree with the Python ones exactly.
 *
 * `vectors.json` is generated by `scripts/testvectors.py`: positions along
 * random games, each with the legal moves, terminal value and network encoding
 * that Python computed. Two implementations of the same rules drift, and the
 * failure mode is quiet - the browser would feed the network inputs it was never
 * trained on while still producing legal, plausible-looking moves.
 */
import { describe, expect, it } from "vitest";
import { Connect4, COLS, ROWS } from "../src/games/connect4";
import vectors from "./vectors.json";

interface Case {
  moves: number[];
  legal: number[];
  terminal: number | null;
  encoded: number[];
}

const game = new Connect4();
const cases = vectors.cases as Case[];

function replay(moves: number[]) {
  let state = game.initialState();
  for (const move of moves) state = game.apply(state, move);
  return state;
}

describe("agreement with the Python implementation", () => {
  it("has vectors to check against", () => {
    expect(vectors.game).toBe("connect4");
    expect(cases.length).toBeGreaterThan(100);
    expect(cases.some((c) => c.terminal !== null)).toBe(true);
  });

  it("shares the same board shape and action count", () => {
    expect([...game.boardShape]).toEqual(vectors.boardShape);
    expect(game.actionSize).toBe(vectors.actionSize);
    expect(game.inputPlanes).toBe(vectors.inputPlanes);
  });

  it("agrees on legal moves", () => {
    for (const testCase of cases) {
      const legal = game.legalActions(replay(testCase.moves));
      expect(legal.map(Number), `moves ${testCase.moves}`).toEqual(testCase.legal);
    }
  });

  it("agrees on terminal values", () => {
    for (const testCase of cases) {
      const value = game.terminalValue(replay(testCase.moves));
      expect(value, `moves ${testCase.moves}`).toBe(testCase.terminal);
    }
  });

  it("agrees on encodings, which is what the network consumes", () => {
    for (const testCase of cases) {
      const encoded = Array.from(game.encode(replay(testCase.moves)));
      expect(encoded, `moves ${testCase.moves}`).toEqual(testCase.encoded);
    }
  });
});

describe("conventions", () => {
  it("starts empty with every column open", () => {
    const state = game.initialState();
    expect(state.board.every((v) => v === 0)).toBe(true);
    expect(game.legalActions(state).every(Boolean)).toBe(true);
    expect(game.terminalValue(state)).toBeNull();
  });

  it("drops pieces to the lowest empty cell", () => {
    const state = game.apply(game.initialState(), 3);
    // The mover's piece is -1 from the next player's point of view.
    expect(state.board[(ROWS - 1) * COLS + 3]).toBe(-1);
    expect(state.board.filter((v) => v !== 0).length).toBe(1);
  });

  it("refuses a full column", () => {
    let state = game.initialState();
    for (let i = 0; i < ROWS; i++) state = game.apply(state, 0);
    expect(game.legalActions(state)[0]).toBe(false);
    expect(() => game.apply(state, 0)).toThrow();
  });

  it("never reports a win for the player to move", () => {
    // A win always lands on the loser's turn, so +1 is unreachable here.
    for (const testCase of cases) {
      const value = game.terminalValue(replay(testCase.moves));
      expect(value === null || value === -1 || value === 0).toBe(true);
    }
  });

  it("swaps the two planes on every move", () => {
    const before = game.encode(replay([3, 4, 2]));
    const after = game.encode(game.apply(replay([3, 4, 2]), 5));
    const squares = ROWS * COLS;

    // The opponent's pieces are untouched and are now plane 0.
    expect(Array.from(after.slice(0, squares))).toEqual(
      Array.from(before.slice(squares)),
    );
    // The mover's are now plane 1, with exactly one added.
    const added = Array.from(after.slice(squares)).map((v, i) => v - before[i]);
    expect(added.reduce((a, b) => a + b, 0)).toBe(1);
  });
});
